name: fair_provider
description: An extension library for Fair on the Provider framework.
homepage: https://fair.58.com/
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fair: ^3.4.0
  provider: ^6.0.5
  collection: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2
  fair_compiler: ^1.9.0

dependency_overrides:
  collection: 1.17.0
  fair_version: 3.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/plugin/