name: fair_dart2js
description: Convert individual dart file to js.
version: 1.6.0
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.5.0
  path: ^1.8.0

#dependency_overrides:
#  collection: 1.17.0